/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface X402FeeSplitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FEE_BPS"
      | "MIN_AMOUNT"
      | "acceptOwnership"
      | "authorizedFacilitators"
      | "calculateSplit"
      | "collectedFees"
      | "defaultFeeBps"
      | "emergencyWithdraw"
      | "emergencyWithdrawTo"
      | "facilitatorCount"
      | "getStats"
      | "getTokenFee"
      | "getTokenStats"
      | "isFacilitator"
      | "maxSettlementAmount"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "renounceOwnership"
      | "setDefaultFee"
      | "setFacilitator"
      | "setMaxSettlement"
      | "setTokenFee"
      | "setTokenFeesBatch"
      | "setTokenWhitelisted"
      | "setTokensWhitelistedBatch"
      | "setTreasury"
      | "setWhitelistMode"
      | "splitPayment"
      | "tokenConfigured"
      | "tokenFeeBps"
      | "tokenWhitelisted"
      | "totalSettlements"
      | "totalVolumeByToken"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "whitelistMode"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DefaultFeeUpdated"
      | "EmergencyWithdraw"
      | "FacilitatorUpdated"
      | "MaxSettlementUpdated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentSplit"
      | "TokenFeeUpdated"
      | "TokenWhitelistUpdated"
      | "TreasuryUpdated"
      | "Unpaused"
      | "WhitelistModeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedFacilitators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSplit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawTo",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "facilitatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFacilitator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSettlementAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFacilitator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxSettlement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenFeesBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenWhitelisted",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokensWhitelistedBatch",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "splitPayment",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenConfigured",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenFeeBps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSettlements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolumeByToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelistMode",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_AMOUNT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedFacilitators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "facilitatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSettlementAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFacilitator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenFeesBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokensWhitelistedBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenConfigured",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSettlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolumeByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistMode",
    data: BytesLike
  ): Result;
}

export namespace DefaultFeeUpdatedEvent {
  export type InputTuple = [oldFeeBps: BigNumberish, newFeeBps: BigNumberish];
  export type OutputTuple = [oldFeeBps: bigint, newFeeBps: bigint];
  export interface OutputObject {
    oldFeeBps: bigint;
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FacilitatorUpdatedEvent {
  export type InputTuple = [facilitator: AddressLike, authorized: boolean];
  export type OutputTuple = [facilitator: string, authorized: boolean];
  export interface OutputObject {
    facilitator: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxSettlementUpdatedEvent {
  export type InputTuple = [oldMax: BigNumberish, newMax: BigNumberish];
  export type OutputTuple = [oldMax: bigint, newMax: bigint];
  export interface OutputObject {
    oldMax: bigint;
    newMax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSplitEvent {
  export type InputTuple = [
    token: AddressLike,
    payer: AddressLike,
    recipient: AddressLike,
    grossAmount: BigNumberish,
    netAmount: BigNumberish,
    fee: BigNumberish,
    facilitator: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    payer: string,
    recipient: string,
    grossAmount: bigint,
    netAmount: bigint,
    fee: bigint,
    facilitator: string
  ];
  export interface OutputObject {
    token: string;
    payer: string;
    recipient: string;
    grossAmount: bigint;
    netAmount: bigint;
    fee: bigint;
    facilitator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFeeUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    oldFeeBps: BigNumberish,
    newFeeBps: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    oldFeeBps: bigint,
    newFeeBps: bigint
  ];
  export interface OutputObject {
    token: string;
    oldFeeBps: bigint;
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWhitelistUpdatedEvent {
  export type InputTuple = [token: AddressLike, whitelisted: boolean];
  export type OutputTuple = [token: string, whitelisted: boolean];
  export interface OutputObject {
    token: string;
    whitelisted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistModeUpdatedEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface X402FeeSplitter extends BaseContract {
  connect(runner?: ContractRunner | null): X402FeeSplitter;
  waitForDeployment(): Promise<this>;

  interface: X402FeeSplitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  authorizedFacilitators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  calculateSplit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [[bigint, bigint] & { netAmount: bigint; feeAmount: bigint }],
    "view"
  >;

  collectedFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  defaultFeeBps: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdrawTo: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  facilitatorCount: TypedContractMethod<[], [bigint], "view">;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        settlements: bigint;
        treasuryAddr: string;
        defaultFee: bigint;
        numFacilitators: bigint;
        isPaused: boolean;
        isWhitelistMode: boolean;
      }
    ],
    "view"
  >;

  getTokenFee: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getTokenStats: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, boolean, boolean, bigint, bigint] & {
        feeBps: bigint;
        configured: boolean;
        whitelisted: boolean;
        feesCollected: bigint;
        volumeSettled: bigint;
      }
    ],
    "view"
  >;

  isFacilitator: TypedContractMethod<
    [facilitator: AddressLike],
    [boolean],
    "view"
  >;

  maxSettlementAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDefaultFee: TypedContractMethod<
    [feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFacilitator: TypedContractMethod<
    [facilitator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setMaxSettlement: TypedContractMethod<
    [_maxAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenFee: TypedContractMethod<
    [token: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenFeesBatch: TypedContractMethod<
    [tokens: AddressLike[], feesBps: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setTokenWhitelisted: TypedContractMethod<
    [token: AddressLike, whitelisted: boolean],
    [void],
    "nonpayable"
  >;

  setTokensWhitelistedBatch: TypedContractMethod<
    [tokens: AddressLike[], whitelisted: boolean],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setWhitelistMode: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  splitPayment: TypedContractMethod<
    [
      token: AddressLike,
      payer: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [[bigint, bigint] & { netAmount: bigint; feeAmount: bigint }],
    "nonpayable"
  >;

  tokenConfigured: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  tokenFeeBps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  tokenWhitelisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  totalSettlements: TypedContractMethod<[], [bigint], "view">;

  totalVolumeByToken: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  whitelistMode: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedFacilitators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "calculateSplit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [[bigint, bigint] & { netAmount: bigint; feeAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdrawTo"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "facilitatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        settlements: bigint;
        treasuryAddr: string;
        defaultFee: bigint;
        numFacilitators: bigint;
        isPaused: boolean;
        isWhitelistMode: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenFee"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenStats"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, boolean, boolean, bigint, bigint] & {
        feeBps: bigint;
        configured: boolean;
        whitelisted: boolean;
        feesCollected: bigint;
        volumeSettled: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFacilitator"
  ): TypedContractMethod<[facilitator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxSettlementAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultFee"
  ): TypedContractMethod<[feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFacilitator"
  ): TypedContractMethod<
    [facilitator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxSettlement"
  ): TypedContractMethod<[_maxAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenFee"
  ): TypedContractMethod<
    [token: AddressLike, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenFeesBatch"
  ): TypedContractMethod<
    [tokens: AddressLike[], feesBps: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenWhitelisted"
  ): TypedContractMethod<
    [token: AddressLike, whitelisted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokensWhitelistedBatch"
  ): TypedContractMethod<
    [tokens: AddressLike[], whitelisted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWhitelistMode"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "splitPayment"
  ): TypedContractMethod<
    [
      token: AddressLike,
      payer: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish
    ],
    [[bigint, bigint] & { netAmount: bigint; feeAmount: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenConfigured"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenFeeBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenWhitelisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalSettlements"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolumeByToken"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "whitelistMode"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "DefaultFeeUpdated"
  ): TypedContractEvent<
    DefaultFeeUpdatedEvent.InputTuple,
    DefaultFeeUpdatedEvent.OutputTuple,
    DefaultFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "FacilitatorUpdated"
  ): TypedContractEvent<
    FacilitatorUpdatedEvent.InputTuple,
    FacilitatorUpdatedEvent.OutputTuple,
    FacilitatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxSettlementUpdated"
  ): TypedContractEvent<
    MaxSettlementUpdatedEvent.InputTuple,
    MaxSettlementUpdatedEvent.OutputTuple,
    MaxSettlementUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSplit"
  ): TypedContractEvent<
    PaymentSplitEvent.InputTuple,
    PaymentSplitEvent.OutputTuple,
    PaymentSplitEvent.OutputObject
  >;
  getEvent(
    key: "TokenFeeUpdated"
  ): TypedContractEvent<
    TokenFeeUpdatedEvent.InputTuple,
    TokenFeeUpdatedEvent.OutputTuple,
    TokenFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWhitelistUpdated"
  ): TypedContractEvent<
    TokenWhitelistUpdatedEvent.InputTuple,
    TokenWhitelistUpdatedEvent.OutputTuple,
    TokenWhitelistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistModeUpdated"
  ): TypedContractEvent<
    WhitelistModeUpdatedEvent.InputTuple,
    WhitelistModeUpdatedEvent.OutputTuple,
    WhitelistModeUpdatedEvent.OutputObject
  >;

  filters: {
    "DefaultFeeUpdated(uint256,uint256)": TypedContractEvent<
      DefaultFeeUpdatedEvent.InputTuple,
      DefaultFeeUpdatedEvent.OutputTuple,
      DefaultFeeUpdatedEvent.OutputObject
    >;
    DefaultFeeUpdated: TypedContractEvent<
      DefaultFeeUpdatedEvent.InputTuple,
      DefaultFeeUpdatedEvent.OutputTuple,
      DefaultFeeUpdatedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "FacilitatorUpdated(address,bool)": TypedContractEvent<
      FacilitatorUpdatedEvent.InputTuple,
      FacilitatorUpdatedEvent.OutputTuple,
      FacilitatorUpdatedEvent.OutputObject
    >;
    FacilitatorUpdated: TypedContractEvent<
      FacilitatorUpdatedEvent.InputTuple,
      FacilitatorUpdatedEvent.OutputTuple,
      FacilitatorUpdatedEvent.OutputObject
    >;

    "MaxSettlementUpdated(uint256,uint256)": TypedContractEvent<
      MaxSettlementUpdatedEvent.InputTuple,
      MaxSettlementUpdatedEvent.OutputTuple,
      MaxSettlementUpdatedEvent.OutputObject
    >;
    MaxSettlementUpdated: TypedContractEvent<
      MaxSettlementUpdatedEvent.InputTuple,
      MaxSettlementUpdatedEvent.OutputTuple,
      MaxSettlementUpdatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentSplit(address,address,address,uint256,uint256,uint256,address)": TypedContractEvent<
      PaymentSplitEvent.InputTuple,
      PaymentSplitEvent.OutputTuple,
      PaymentSplitEvent.OutputObject
    >;
    PaymentSplit: TypedContractEvent<
      PaymentSplitEvent.InputTuple,
      PaymentSplitEvent.OutputTuple,
      PaymentSplitEvent.OutputObject
    >;

    "TokenFeeUpdated(address,uint256,uint256)": TypedContractEvent<
      TokenFeeUpdatedEvent.InputTuple,
      TokenFeeUpdatedEvent.OutputTuple,
      TokenFeeUpdatedEvent.OutputObject
    >;
    TokenFeeUpdated: TypedContractEvent<
      TokenFeeUpdatedEvent.InputTuple,
      TokenFeeUpdatedEvent.OutputTuple,
      TokenFeeUpdatedEvent.OutputObject
    >;

    "TokenWhitelistUpdated(address,bool)": TypedContractEvent<
      TokenWhitelistUpdatedEvent.InputTuple,
      TokenWhitelistUpdatedEvent.OutputTuple,
      TokenWhitelistUpdatedEvent.OutputObject
    >;
    TokenWhitelistUpdated: TypedContractEvent<
      TokenWhitelistUpdatedEvent.InputTuple,
      TokenWhitelistUpdatedEvent.OutputTuple,
      TokenWhitelistUpdatedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WhitelistModeUpdated(bool)": TypedContractEvent<
      WhitelistModeUpdatedEvent.InputTuple,
      WhitelistModeUpdatedEvent.OutputTuple,
      WhitelistModeUpdatedEvent.OutputObject
    >;
    WhitelistModeUpdated: TypedContractEvent<
      WhitelistModeUpdatedEvent.InputTuple,
      WhitelistModeUpdatedEvent.OutputTuple,
      WhitelistModeUpdatedEvent.OutputObject
    >;
  };
}
